<?php

use App\Models\FormFieldLookup;
use Illuminate\Database\Seeder;

class FormFieldLookupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $groups = [
            'campus' => [
                'G' => 'Greensboro (main)',
                'O' => 'Online',
                'S' => 'Off-Site',
            ],
            'college' => [
                'CAS' => 'College of Arts & Sciences',
                'BRYAN' => 'Bryan School of Business and Economics',
                'SOE' => 'School of Education',
                'HHS' => 'School of Health & Human Sciences',
                'LHC' => 'Lloyd Honors College',
                'NUR' => 'School of Nursing',
                'CVPA' => 'College of Visual & Performing Arts',
                'ONL' => 'UNCG Online',
                'DOM' => 'Enrollment Management',
            ],
            'position' => [
                'Instructor' => 'Instructor',
                'Lab Assistant' => 'Lab Assistant (non-student)',
                'Grad Assistant' => 'Graduate Assistant (grad student)',
                'Teaching Assistant' => 'Teaching Assistant (grad student)',
                'Sr. Teaching Assistant' => 'Sr. Teaching Assistant (grad student)',
                'Undergraduate' => 'Undergraduate Student Position',
                'Bio Preparator' => 'Bio Preparator & Coordinator',
                'Stockroom Supervisor' => 'Stockroom Supervisor',
                'Chemistry Lab Manager' => 'Chemistry Lab Manager',
                'IAR Woodshop Supervisor' => 'IAR Woodshop Supervisor',
                'Spanish Tutor' => 'Spanish Tutor',
                'Math & Statistics Help Cen' => 'Math & Statistics Help Center',
                'Student Success Center' => 'Student Success Center',
                'Writing Center Hourly Consulta' => 'Writing Center Hourly Consultant',
                'Writing Center Manager' => 'Writing Center Manager',
                'Writing Center Grad Assistant' => 'Writing Center Graduate Assistant',
                'Writing Center Administrator' => 'Writing Center Administrator',
                'Speaking Center TA' => 'Speaking Center Teaching Assistant (graduate student)',
                'Speaking Center Tutor' => 'Speaking Center Tutor (undergrad student)',
                'Speaking Center' => 'Speaking Center Other Staff',
                'other' => 'other (describe in comments)',
            ],
            'prefix' => [
                'Dr.' => 'Dr.',
                'Ms.' => 'Ms.',
                'Mr.' => 'Mr.',
                'Mx.' => 'Mx.',
            ],
            'course_type' => [
                'LEC' => 'LEC',
                'WEB' => 'WEB',
                'LAB' => 'LAB',
                'DTS' => 'DTS',
            ],
            'meeting_start_end_times' => [
                '0800-1000' => '0800-1000',
                '1010-1210' => '1010-1210',
                '1220-1420' => '1220-1420',
                '1430-1630' => '1430-1630',
                '1700-1900' => '1700-1900',
                '1800-2000' => '1800-2000',
                '1900-2100' => '1900-2100',
                '1430-1700' => '1430-1700',
                '1700-1930' => '1700-1930',
                '1800-2030' => '1800-2030',
                '1830-2130' => '1830-2130'
            ],
            'subject' => [
                'ARS' => 'Academic Recovery Seminar',
                'ACC' => 'Accounting',
                'ADS' => 'African American and African Diaspora Studies',
                'ASL' => 'American Sign Language',
                'ATY' => 'Anthropology',
                'APD' => 'Apparel Product Design',
                'ARE' => 'Art Education',
                'ARH' => 'Art History',
                'RCO' => 'Ashby Residential College',
                'AST' => 'Astronomy',
                'BIO' => 'Biology',
                'BUS' => 'Business Administration',
                'BSA' => 'Business Affairs',
                'CHE' => 'Chemistry and Biochemistry',
                'CHI' => 'Chinese',
                'CCI' => 'Classical Civilization',
                'CSD' => 'Communication Sciences and Disorders',
                'CST' => 'Communication Studies',
                'CTR' => 'Community and Therapeutic Recreation',
                'CTP' => 'Comprehensive Transition and Postsecondary Education',
                'CSC' => 'Computer Science',
                'CRS' => 'Consumer, Apparel, and Retail Studies',
                'CED' => 'Counseling and Educational Development',
                'DCE' => 'Dance',
                'DOL' => 'Division of Online Learning',
                'ECO' => 'Economics',
                'ELC' => 'Educational Leadership and Cultural Foundations',
                'ERM' => 'Educational Research Methodology',
                'ENG' => 'English',
                'ENS' => 'Ensemble',
                'ENT' => 'Entrepreneurship',
                'ENV' => 'Environmental & Sustainability Studies',
                'FIN' => 'Finance',
                'FFL' => 'Foundations for Learning',
                'FRE' => 'French',
                'FMS' => 'Freshman Seminars',
                'GEN' => 'Genetic Counseling',
                'GER' => 'German',
                'GES' => 'Geography, Environment, and Sustainability',
                'GRO' => 'Gerontology',
                'GRK' => 'Greek',
                'GRC' => 'Grogan College',
                'HHS' => 'Health and Human Sciences',
                'HED' => 'Higher Education',
                'HIS' => 'History',
                'HSS' => 'Honors Program',
                'HDF' => 'Human Development and Family Studies',
                'BLS' => 'Humanities',
                'ISM' => 'Information Systems and Operations Management',
                'IPS' => 'Integrated Professional Studies',
                'ISC' => 'Integrated Science',
                'ISL' => 'Integrated Studies Lab',
                'IAR' => 'Interior Architecture',
                'IGS' => 'International and Global Studies',
                'IPC' => 'International Programs',
                'ITA' => 'Italian',
                'JNS' => 'Japanese Studies',
                'KIN' => 'Kinesiology',
                'LLC' => 'Languages, Literatures, and Cultures',
                'LAT' => 'Latin',
                'LIS' => 'Library and Information Studies',
                'MGT' => 'Management',
                'MKT' => 'Marketing Development',
                'MLS' => 'Master of Arts in Liberal Studies',
                'MBA' => 'Master of Business Adminstration',
                'MAS' => 'Masters in Applied Arts and Sciences',
                'MAT' => 'Mathematics',
                'MST' => 'Media Studies',
                'MUS' => 'Music',
                'MUE' => 'Music Education',
                'MUP' => 'Music Performance',
                'NAN' => 'Nanoscience',
                'NUR' => 'Nursing',
                'NTR' => 'Nutrition',
                'PCS' => 'Peace and Conflict Studies',
                'PHI' => 'Philosophy',
                'PHY' => 'Physics',
                'PSC' => 'Political Science',
                'POR' => 'Portuguese',
                'PRV' => 'Provost',
                'PSY' => 'Psychology',
                'HEA' => 'Public Heath',
                'REL' => 'Religious Studies',
                'RCS' => 'Retailing and Consumer Studies',
                'RUS' => 'Russian',
                'SOE' => 'School of Education',
                'SON' => 'School of Nursing',
                'SSC' => 'Social Sciences',
                'SWK' => 'Social Work',
                'SOC' => 'Sociology',
                'SPA' => 'Spanish',
                'SC' => 'Speaking Center',
                'SES' => 'Specialized Education Services',
                'STA' => 'Statistics',
                'STR' => 'Strong College',
                'ST' => 'Student Success Center',
                'ART' => 'Studio Art',
                'SCM' => 'Supply Chain Management',
                'STH' => 'Sustainable Tourism and Hospitality',
                'TED' => 'Teacher Education',
                'THR' => 'Theatre',
                'UNS' => 'University Studies',
                'VPA' => 'Visual and Performing Arts',
                'WCV' => 'Western Civilization',
                'WGS' => 'Women\'s and Gender Studies',
                'WC' => 'Writing Center',
                'DAC' => 'Digital ACT Studio'
            ],
        ];

        foreach ($groups as $group => $members) {
            foreach ($members as $value => $name) {
                FormFieldLookup::firstOrCreate(
                    ['field' => $group, 'abbreviation' => $value],
                    ['name' => $name]
                );
            }
        }
    }
}
