<?php
/** @var Factory $factory */

use App\Models\Letter;
use Faker\Generator as Faker;
use Illuminate\Database\Eloquent\Factory;

$factory->define(Letter::class, function (Faker $faker) {
    return [
        'body' => (string) '<p><strong>Division of Online Learning</strong></p><p>Becher-Weaver Building<br>915 Northridge Street<br>PO Box 26170<br>Greensboro, NC 27402-6170</p><p>336.315.7044 Phone&nbsp;&nbsp;&nbsp;&nbsp;336.315.7767 Fax</p><p>online.uncg.edu</p><p>Dear Made-up Person,</p><p>This is a fake letter generated by our database seeder.</p><p>'.$faker->paragraph(3, true).'</p><p>'.$faker->paragraph(4, true).'</p><p>Sincerely,</p><p>The Forms System</p>',
        'term_id' => $faker->randomNumber(1),
        'user_id' => $faker->randomNumber(1),
    ];
});
